version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces:cached
    command: npm start
    depends_on:
      - db
    networks:
      - pymorfosis-network

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - pymorfosis-network

  server:
    build: ./server
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - pymorfosis-network

volumes:
  postgres-data:

networks:
  pymorfosis-network:
    driver: bridge

