version: '3.8'

services:
  app:
    build:
      # Ajusta el contexto para que coincida con la ubicación del Dockerfile
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspaces:cached
    # Este comando evita que el contenedor se cierre al finalizar el proceso
    command: sleep infinity
    # Dentro del contenedor, al usar network_mode se conecta a la BD a través de localhost
    network_mode: service:db

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PyMorfosis
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

